version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "1234:6379"
      - "8001:8001"
    volumes:
      - ./.cache_redis_data:/data
      - ./redis.conf:/redis-stack.conf
    networks:
      - cache_network

networks:
  cache_network:
    driver: bridge
